//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_QUALIFICATION
    {
        public int Employee_Id { get; set; }
        public int Q_id { get; set; }
        public double Marks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual QualificationList QualificationList { get; set; }
    }
}
