//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCSTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EMP_QUALIFICATION = new HashSet<EMP_QUALIFICATION>();
        }
    
        public int Employee_Id { get; set; }
        public string Emp_Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Entry_by { get; set; }
        public System.DateTime Entry_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_QUALIFICATION> EMP_QUALIFICATION { get; set; }
    }
}
